### ISSUE TITLE
SF.rb February Meetup

### ISSUE THREAD

**Issue by lilliealbert** [sfdotrb/organizing#2]
### Who's doing what? :fist:
- Venue liaison: @aneyzberg 
- Speaker wrangler: @lilliealbert
- Meetup poster / question answerer: @lilliealbert
- Emcee: @lilliealbert
- Check in: @stellacotton
### Planning Checklist :heavy_check_mark:
- [x] Date picked: **Tuesday, February 23**
- [x] Venue and sponsor found
- [x] 5-7 min speaking slot filled
- [x] 20 min speaking slot no. 1 filled
- [x] 20 min speaking slot no. 2 filled
- [x] Event posted to Meetup
- [x] Food / drinks confirmed
- [x] Emcee confirmed
- [x] Security / checkins wrangler confirmed
#### Week-of Checklist
- [x] Reconfirm food and drink plans
- [ ] Reconfirm speaker arrival time and tech needs
- [ ] Confirm who's got what in running the event
- [ ] Go over physical object inventory:
  - [x] Name tags
  - [ ] Ruby Cutie stickers
- [ ] Create welcome slide with suggested question topic

**Comment by lilliealbert** [comment]
Speaker lineup:

**How to Lose Friends and Alienate People with Code**
by Andy Cernera

Do you want to teach someone to code? Do you care about this person in any way? If so, stop right there and come listen to this informative talk on the dos and don'ts of teaching a loved one the most frustrating thing they will ever encounter.

Hi I'm Andy. I'm a software engineer, dungeon master, and all-around show-offy jerk. I love Ruby, love (and hate) Javascript, and sometimes I waste my time with other languages.

---

**How to look at MRI's source code and not be totally terrified**
by Franck Verrot

Random behavior can be understood, but digging into MRI's C implementation isn't straightforward. In this talk, we'll take a look at real-world random behavior, and understand how we can write better Ruby code.

Franck is a senior Software Engineer. He loves working on performance subjects, distributed systems and databases.

---

**Stop Building Services**
by Rachel Myers

This talk runs through personal examples of services creating more brittle systems with worse failure cases. Building on those failure scenarios, I draw out guidelines for if, when, and how to consider Service Oriented Architecture

Rachel is a developer at GitHub who loves Ruby and JavaScript. In the past she's done front end performance (and monitoring) and email. In her free time she likes doing her nails and playing legos, which don't really go together well.

**Comment by aneyzberg** [comment]
Venue info:
Date: 3/23/16
Time: 6:30pm - 9:00pm. 
Address: 23 Geary St #500, San Francisco, CA 94108

Emailed about bike parking - need to hear back
We will need to provide a list for security for the event and will need someone downstairs to help do checkin.

Catie Schlensker is our contact there.

**Comment by lilliealbert** [comment]
It happened! The talks were great and Mavenlink were gracious hosts.

Things we learned:
- We should make sure there's a PA — never know when there will be construction outside
- We should come up with a short list of caterers we :heart: and encourage companies to use those for maximum food happiness
- If security is nightmarish, we have to send a second person down to help with checkins and elevatoring
- We should come up with a speaker confirmation email template that includes the content guidelines.

@stellacotton / @aneyzberg, any other learnings to share with this public record?

**Comment by stellaconyer** [comment]
- Yes, people can give a short pitch for other things but they should message us ahead of time. If someone asks, tell them to message us through the meetup to get on the schedule. Set expectations around length and whether they can use slides.
- Make day of/week of action items clearly associated with the role (e.g. check in person is responsible for name tags, downloading check in doc, bringing a computer to check people in, speaker wrangler is responsible for sending the speaker confirmation email, meetup poster is responsible for sending out the day-of-email etc.)
- Let’s set a specific time for the organizers to be there so the venue knows what time to expect us and we know what time to be there
