### ISSUE TITLE
SF.rb April meetup

### ISSUE THREAD

**Issue by lilliealbert** [sfdotrb/organizing#4]
### Who's doing what? :fist:
- Venue liaison: @aneyzberg 
- Speaker wrangler: @aneyzberg 
- Meetup poster / question answerer: @sienatime
- Emcee: @aneyzberg 
### Planning Checklist :heavy_check_mark:
- [x] Date picked: **Tuesday, April 26, 2016**
- [x] Venue and sponsor found: **Instacart**
- [x] 5-7 min speaking slot filled - Pam Mangan on non-profits and tech
- [x] 20 min speaking slot no. 1 filled - Lillie on running a good internship program
- [x] 20 min speaking slot no. 2 filled - Eric Saxby on Rabbit MQ
- [x] Event posted to Meetup
- [x] Food / drinks confirmed
- [x] Emcee confirmed
- [x] Security / checkins wrangler confirmed: @sienatime
##### Speaker Wrangler
- [x] Reconfirm speaker arrival time and tech needs
##### Venue Liason
- [x] Reconfirm food and drink plans
- [x] Send security check-in list day before - make sure list includes wait-listed folks and speakers
##### Meetup Poster/Question Answerer
- [x] Close wait list the day before
- [x] Send out RSVP reminder email & final logistics reminder
- [x] Send followup thank you email after the event
##### Check In Person
- [x] Download doc and bring computer for check in
##### Misc
- [x] Confirm who's got what in running the event
- [x] Go over physical object inventory:
  - [x] Name tags
  - [ ] Ruby Cutie stickers
- [x] Create welcome slide with suggested question topic

**Comment by aneyzberg** [comment]
Instacart has agreed to host.
Date: 4/26
Time: 6:30 - 9:00pm
Address: 50 Beale St. 11th Floor - Blue Shield Building
Contact: Nicholas Hong
