### ISSUE TITLE
SF.rb May meetup

### ISSUE THREAD

**Issue by lilliealbert** [sfdotrb/organizing#5]
### Who's doing what? :fist:
- Venue liaison: @stellacotton 
- Speaker wrangler: @stellacotton 
- Meetup poster / question answerer: @sienatime
- Emcee: @stellacotton
### Planning Checklist :heavy_check_mark:
- [x] Date picked: **May 11th**
- [x] Venue and sponsor found: **Github**
- [x] Programming confirmed: **Sandi Metz and Avdi Grimm**
- [x] Recruit additional volunteer
- [x] Event posted to Meetup
- [x] Food / drinks confirmed
- [x] Emcee confirmed
- [x] Security / checkins wrangler confirmed

---
##### Speaker Wrangler
- [x] Reconfirm speaker arrival time and tech needs
##### Venue Liason
- [x] Reconfirm food and drink plans
- [ ] Send security check-in list day before - make sure list includes wait-listed folks and speakers
##### Meetup Poster/Question Answerer
- [x] Close wait list the day before
- [x] Send out RSVP reminder email & final logistics reminder
- [ ] Send followup thank you email after the event
##### Check In Person
- [x] Download doc and bring computer for check in
##### Misc
- [x] Confirm who's got what in running the event
- [x] Go over physical object inventory:
  - [x] Name tags
  - [x] Ruby Cutie stickers
  - [x] Welcome sign
- [x] Create welcome slide with suggested question topic

**Comment by sienaigg** [comment]
Retro thoughts:
- Separate checkin station + nametag station was nice as you didn't get a bottleneck at checkin
- People are very interested in the "what topics people want to hear" list so maybe we should make more of an effort of publishing/curating that list
- Jennifer T. and Sarah K. were very helpful ad hoc volunteers and we'd be happy to have them back (or even add them to the organizing team if they're interested)
- We're awesome and making positive change in the SF Ruby community :)
