### ISSUE TITLE
SF.rb June Meetup

### ISSUE THREAD

**Issue by lilliealbert** [sfdotrb/organizing#6]
### Who's doing what? :fist:
- Venue liaison: @sienatime
- Speaker wrangler:  @stellacotton 
- Meetup poster / question answerer: @stellacotton 
- Emcee: @aneyzberg
### Planning Checklist :heavy_check_mark:
- [x] Date picked: June 7, 2016
- [x] Venue and sponsor found: Heroku
- [x] 5-7 min speaking slot filled
- [x] 20 min speaking slot no. 1 filled
- [x] 20 min speaking slot no. 2 filled
- [x] Event posted to Meetup
- [x] Food / drinks confirmed
- [x] Emcee confirmed
- [x] Security / checkins wrangler confirmed

---
##### Speaker Wrangler
- [x] Reconfirm speaker arrival time and tech needs
##### Venue Liason
- [x] Reconfirm food and drink plans
- [x] Send security check-in list day before - make sure list includes wait-listed folks and speakers
##### Meetup Poster/Question Answerer
- [x] Send out RSVP reminder email & final logistics reminder - Lillie going to do it
- [x] Send followup thank you email after the event
##### Check In Person
- [x] Download doc and bring computer for check in - Lillie
##### Misc
- [ ] Confirm who's got what in running the event
- [ ] Go over physical object inventory:
  - [ ] Name tags: Stella
  - [ ] Ruby Cutie stickers: Stella
  - [x] Welcome sign: Siena
- [x] Create welcome slide with suggested question topic

**Comment by sienatime** [comment]
Heroku:
- everyone needs to sign an NDA, we can get an electronic version to put on the Meetup page
- Security isn't strict so we can let everyone in, but also should send list of names ahead of time
- Heroku security will give everyone a wristband for the event and a 2nd one if they are 21+ and want to drink
- they have handheld and lapel mics available
- they might provide some Heroku swag
- bike parking is available

**Comment by aneyzberg** [comment]
I can emcee again, unless someone else is already planing on doing it?
